//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class For_Rent
    {
        public int Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<System.DateTime> Available_From { get; set; }
        public Nullable<double> Advance_Amount { get; set; }
    }
}
